#!/bin/csh
#PBS -l select=1:ncpus=1:model=ivy+39:ncpus=20:model=ivy
##PBS -l walltime=54:00:00
##PBS -q vlong
#PBS -l walltime=2:00:00
#PBS -q devel
#PBS -j oe
#PBS -m abe

module purge
#module load comp-intel/2012.0.032 mpi-sgi/mpt netcdf/4.0
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 027
cd $PBS_O_WORKDIR
limit stacksize unlimited
#./modpickup
mpiexec -np 767 dplace -s1 ./mitgcmuv
