#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm_contrib/llc_hires/llc_4320/code-async/linux_amd64_ifort+mpi_ice_nas,v 1.4 2016/04/02 01:27:56 dimitri Exp $
# $Name:  $

# Used with:
# module load comp-intel/2015.0.090 test/mpt.2.11r8 netcdf/4.0

FC=ifort
CC=icc

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DALLOW_ASYNCIO -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
OMPFLAG='-openmp'
CFLAGS='-fPIC'
LDADD='-shared-intel'

LIBS='-L/nasa/sgi/mpt/2.08r7/lib -lmpi -L/nasa/netcdf/4.0/lib -lnetcdf'
INCLUDES='-I/nasa/sgi/mpt/2.08r7/include -I/nasa/netcdf/4.0/include'
INCLUDEDIRS='/nasa/sgi/mpt/2.08r7/include'
MPIINCLUDEDIR='/nasa/sgi/mpt/2.08r7/include'
MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
MPI_HEADER_FILES_INC='./mpi_headers/mpif.h ./mpi_headers/mpiof.h ./mpi_headers/mpif_parameters.h'

NOOPTFLAGS='-O1 -fp-model precise'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -align"
    FOPTIM='-O3 -ipo -axCORE-AVX2,AVX -xSSE4.1 -ip -fp-model precise -traceback -ftz'
    NOOPTFILES='seaice_growth.F calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -noalign"
    FOPTIM='-O0'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

#- For really big executable (> 2 GB), uncomment following 2 lines
FFLAGS="$FFLAGS -mcmodel=medium -shared-intel"
CFLAGS="$CFLAGS -mcmodel=medium -shared-intel"
