#!/bin/bash 
##SBATCH -p dragonfly1,dragonfly2,dragonfly3,dragonfly4,compute
#SBATCH -N 120 
#SBATCH --ntasks-per-node=10
#SBATCH -t 00:30:00
#SBATCH -J test
ulimit -a
source /gpfs/bb0/scinet/bin/intel.sh
source /gpfs/bb0/scinet/bin/intelmpi.sh
cd ~/MITgcm/run
mpiexec.hydra -perhost 10 -n 1152 ./mitgcmuv
