#! /usr/bin/env bash

# tested on NASA Ames athena with default modules
# module list
# Currently Loaded Modulefiles:
# 1) cray-libpals/1.7.1   6) perftools-base/25.09.0         11) cray-mpich/8.1.33    
# 2) cray-pals/1.7.1      7) xpmem/1.0.1-1.4_gf67ddfb318d4  12) cray-libsci/25.09.0  
# 3) craype-x86-turin     8) cce/20.0.0                     13) PrgEnv-cray/8.6.0    
# 4) libfabric/12.0       9) craype/2.7.35                  
# 5) craype-network-ofi  10) cray-dsmml/0.3.1               

CC=cc
FC=ftn
F90C=ftn
LINK='ftn -h byteswapio'
DEFINES='-DWORDLENGTH=4'
CPP='cpp -traditional -P'
NOOPTFLAGS='-O0'
NOOPTFILES=''
FFLAGS="$FFLAGS"
if test "x$IEEE" = x ; then     #- with optimisation:
    FOPTIM='-O3 -hfp3'
else
  if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
    FOPTIM='-O0 -hfp0'
  else                          #- development/check options:
    FOPTIM='-O0 -hfp0'
    FOPTIM="$FOPTIM -g -hfp0 -Rbc -rm -hmsgs -hnegmsgs"
  fi
fi
F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS="-O0 $MCMODEL"
INCLUDEDIRS=''
INCLUDES=''
LIBS=''
MPI_ROOT="/opt/cray/pe/mpich/8.1.33/ofi/intel/2022.1"
MPI_INC_DIR="${MPI_ROOT}/include"
LIBS="$LIBS -L${MPI_ROOT}/lib -lmpi"
INCLUDES="$INCLUDES -I${MPI_INC_DIR}"
MPIINCLUDEDIR="$MPI_INC_DIR"
linux_amd64_ifort+mpi_cray_nas (END)
