#!/bin/bash -l
##SBATCH -p dragonfly1,dragonfly2,dragonfly3,dragonfly4,compute
#SBATCH -N 1200
#SBATCH --ntasks-per-node=32
#SBATCH -t 08:00:00
#SBATCH -J test
source /gpfs/fs1/scinet/bin/intel.sh
source /gpfs/fs1/scinet/bin/intelmpi.sh
cd /gpfs/fs0/tempscratch/dmenemen/MITgcm/run_250m_264l_async
mpiexec.hydra -n 38400 ./mitgcmuv
