#!/bin/bash
#Build executable for llc540 with latest MITgcm code on pleiades
 git clone https://github.com/MITgcm-contrib/llc_hires.git
 git clone https://github.com/MITgcm/MITgcm.git
 MOD90="../../llc_hires/llc_90/tides_exps"
 MOD540="../../llc_hires/llc_540/tides_exp"

 cd MITgcm
 cd pkg
 ln -s ${MOD90}/pkg_tides tides
 cd ..
 mkdir build run
 cd build
 sed "s|useMYPACKAGE|&, useTIDES|" ../model/inc/PARAMS.h>PARAMS.h
 ## if you are a csh person you want to uncomment the following line
 # source /usr/share/modules/init/bash
 module purge
 module load comp-intel mpi-hpe/mpt hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
 ../tools/genmake2 -of ../tools/build_options/linux_amd64_ifort+mpi_ice_nas -mo ${MOD540}/code -mpi
 sed -i "s|-lnetcdff -lnetcdf|& -L${MOD90}/lib -lspice|" Makefile
 make depend
 make -j 16
 cd ..

# era5 forcing
#run: copy from  ~/llc_hires/llc_540/readme
 cd run
 cp ${MOD540}/input/* . 
 ln -sf /nobackup/hzhang1/pub/llc540/RUN2/pickup*1440.*ta .
 ln -sf /nobackup/hzhang1/pub/llc540/RUN2/kernels .
 ln -sf /nobackup/hzhang1/pub/llc540/RUN2/tile* .
 ln -sf /nobackup/hzhang1/pub/llc540/RUN2/BATHY* .
 ln -sf /nobackup/hzhang1/pub/llc540/RUN2/DIFFKR* .
 ln -sf /nobackup/hzhang1/pub/llc540/RUN2/runoff* .
 ln -sf /nobackup/hzhang1/forcing/era5 .
 ln -sf ../build/mitgcmuv mitgcmuv
 ln -sf data.exch2_60_EXP2 data.exch2
 qsub job_bro_llc540_60

