#!/bin/csh
##PBS -l select=1:ncpus=1:model=sky_ele+56:ncpus=40:model=sky_ele
#PBS -l select=18:ncpus=128:model=rom_ait
##PBS -q vlong
##PBS -l walltime=42:00:00
#PBS -q devel
#PBS -l walltime=2:00:00
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 2229 ./mitgcmuv

