#!/bin/bash -l
##SBATCH -p dragonfly1,dragonfly2,dragonfly3,dragonfly4,compute
#SBATCH -N 922
#SBATCH --ntasks-per-node=40
#SBATCH -t 08:00:00
#SBATCH -J test
source /gpfs/fs1/scinet/bin/intel.sh
source /gpfs/fs1/scinet/bin/intelmpi.sh
cd ~/MITgcm/run
mpiexec.hydra -n 36864 ./mitgcmuv
