#!/bin/csh
#PBS -l select=6:ncpus=20:model=ivy
#below 2 lines for test:
#PBS -l walltime=2:00:00
#PBS -q devel
#below 2 lines for production:
##PBS -l walltime=24:00:00
##PBS -q long
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 113 ./mitgcmuv
