#!/bin/csh
#PBS -l select=39:ncpus=20:model=ivy
##PBS -q long
##PBS -l walltime=42:00:00
#PBS -q devel
#PBS -l walltime=2:00:00
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

cd $PBS_O_WORKDIR
limit stacksize unlimited
#./modpickup
mpiexec -np 784 ./mitgcmuv

